services:
  - type: web
    name: medigaurd
    runtime: node
    rootDir: server
    buildCommand: npm install && cd ../client && npm install && npm run build && mkdir -p ../server/public && cp -r dist/* ../server/public/
    startCommand: node db/seed.js && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 5000
